version: '3.8'

services:
  database:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: hung060503
      MYSQL_DATABASE: demo_db
    ports:
      - "3307:3306"
    networks:
      - app-network
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: ./backend
    container_name: flask_container
    image: hungtran6503/demo8:1.0
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=database
    depends_on:
      - database
    networks:
      - app-network

networks:
  app-network:
